// Personal Details Screen
export const ADD_PERSONAL_DETAILS = 'ADD_PERSONAL_DETAILS';
export const DELETE_PERSONAL_DETAILS = 'DELETE_PERSONAL_DETAILS';

//Declaration Screen
export const ADD_DECLARATION_DETAILS = 'ADD_DECLARATION_DETAILS';
export const DELETE_DECLARATION_DETAILS = 'DELETE_DECLARATION_DETAILS';

